version: '3'
services:
  kdc:
    build: ./kdc
    volumes:
      - ./kdc/start.sh:/start.sh
      - keytab:/keytab
  znbase:
    image: ubuntu:xenial-20170214
    depends_on:
      - kdc
    command: /znbase/znbase --certs-dir=/certs start --listen-addr znbase
    environment:
      - KRB5_KTNAME=/keytab/znbase.keytab
    volumes:
      - ../../.localcluster.certs:/certs
      - keytab:/keytab
      - ../../../../znbase-linux-2.6.32-gnu-amd64:/znbase/znbase
  psql:
    build: ./psql
    depends_on:
      - znbase
    environment:
      - PGHOST=znbase
      - PGPORT=26257
      - PGSSLCERT=/certs/node.crt
      - PGSSLKEY=/certs/node.key
    volumes:
      - ./kdc/krb5.conf:/etc/krb5.conf
      - ./psql/gss_test.go:/test/gss_test.go
      - ./psql/start.sh:/start.sh
      - ../../.localcluster.certs:/certs
volumes:
  keytab:
