apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init-secure
  labels:
    app: znbasedb
spec:
  template:
    spec:
      serviceAccountName: znbasedb
      initContainers:
      # The init-certs container sends a certificate signing request to the
      # kubernetes cluster.
      # You can see pending requests using: kubectl get csr
      # CSRs can be approved using:         kubectl certificate approve <csr name>
      #
      # In addition to the client certificate and key, the init-certs entrypoint will symlink
      # the cluster CA to the certs directory.
      - name: init-certs
        image: znbasedb/znbase-k8s-request-cert:0.4
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/ash"
        - "-ecx"
        - "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/znbase-certs -type=client -user=root -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: client-certs
          mountPath: /znbase-certs
      containers:
      - name: cluster-init
        image: znbasedb/znbase:v2.1.6
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: client-certs
          mountPath: /znbase-certs
        command:
          - "/znbase/znbase"
          - "init"
          - "--certs-dir=/znbase-certs"
          - "--host=znbasedb-0.znbasedb"
      restartPolicy: OnFailure
      volumes:
      - name: client-certs
        emptyDir: {}
