  before_script:
    - pwd
    - whoami
    - source ~/.bashrc
    - echo $PATH
    - go version
    - docker version
  stages:
    - lint
    - build
    - test
    - testlogic
  cache:
    paths:
      - .buildinfo/
      - artifacts/
      - c-deps/jemalloc/
  lint_stage:
    stage: lint
    only:
      - merge_request
      - develop@newsql-sql/znbase
    tags:
      - sql-runner-udr
    script:
      - ./build/builder.sh env ZNBASE_LOGIC_TEST_SKIP=true stdbuf -oL -eL make lint TESTTIMEOUT=45m USE_ROCKSDB_ASSERTIONS=1 2>&1
      - ./ci/git-check.sh
  build_stage:
    stage: build
    only:
      - merge_request
      - develop@newsql-sql/znbase
    tags:
      - sql-runner-udr
    script:
      - ./build/builder.sh mkrelease linux-gnu
      - ./ci/git-check.sh
  test_stage:
    stage: test
    only:
      - merge_request
      - develop@newsql-sql/znbase
    tags:
      - sql-runner-udr
    script:
      - ./build/builder.sh env ZNBASE_NIGHTLY_STRESS=true stdbuf -oL -eL make test TESTTIMEOUT=45m 2>&1
  testlogic_stage:
    stage: testlogic
    only:
      - merge_request
      - develop@newsql-sql/znbase
    tags:
      - sql-runner-udr
    script:
      - ./build/builder.sh stdbuf -oL -eL make testlogic TESTTIMEOUT=45m 2>&1
