// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: roachpb/io-formats.proto

package roachpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DUMPFileFormat int32

const (
	DUMPFileFormat_TABLE    DUMPFileFormat = 0
	DUMPFileFormat_DATABASE DUMPFileFormat = 1
	DUMPFileFormat_SCHEMA   DUMPFileFormat = 2
)

var DUMPFileFormat_name = map[int32]string{
	0: "TABLE",
	1: "DATABASE",
	2: "SCHEMA",
}
var DUMPFileFormat_value = map[string]int32{
	"TABLE":    0,
	"DATABASE": 1,
	"SCHEMA":   2,
}

func (x DUMPFileFormat) Enum() *DUMPFileFormat {
	p := new(DUMPFileFormat)
	*p = x
	return p
}
func (x DUMPFileFormat) String() string {
	return proto.EnumName(DUMPFileFormat_name, int32(x))
}
func (x *DUMPFileFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DUMPFileFormat_value, data, "DUMPFileFormat")
	if err != nil {
		return err
	}
	*x = DUMPFileFormat(value)
	return nil
}
func (DUMPFileFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{0}
}

type IOFileFormat_FileFormat int32

const (
	IOFileFormat_Unknown      IOFileFormat_FileFormat = 0
	IOFileFormat_CSV          IOFileFormat_FileFormat = 1
	IOFileFormat_MysqlOutfile IOFileFormat_FileFormat = 2
	IOFileFormat_Mysqldump    IOFileFormat_FileFormat = 3
	IOFileFormat_PgCopy       IOFileFormat_FileFormat = 4
	IOFileFormat_PgDump       IOFileFormat_FileFormat = 5
	IOFileFormat_TXT          IOFileFormat_FileFormat = 6
	IOFileFormat_ZNBaseDUMP   IOFileFormat_FileFormat = 7
	IOFileFormat_Kafka        IOFileFormat_FileFormat = 8
)

var IOFileFormat_FileFormat_name = map[int32]string{
	0: "Unknown",
	1: "CSV",
	2: "MysqlOutfile",
	3: "Mysqldump",
	4: "PgCopy",
	5: "PgDump",
	6: "TXT",
	7: "ZNBaseDUMP",
	8: "Kafka",
}
var IOFileFormat_FileFormat_value = map[string]int32{
	"Unknown":      0,
	"CSV":          1,
	"MysqlOutfile": 2,
	"Mysqldump":    3,
	"PgCopy":       4,
	"PgDump":       5,
	"TXT":          6,
	"ZNBaseDUMP":   7,
	"Kafka":        8,
}

func (x IOFileFormat_FileFormat) Enum() *IOFileFormat_FileFormat {
	p := new(IOFileFormat_FileFormat)
	*p = x
	return p
}
func (x IOFileFormat_FileFormat) String() string {
	return proto.EnumName(IOFileFormat_FileFormat_name, int32(x))
}
func (x *IOFileFormat_FileFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IOFileFormat_FileFormat_value, data, "IOFileFormat_FileFormat")
	if err != nil {
		return err
	}
	*x = IOFileFormat_FileFormat(value)
	return nil
}
func (IOFileFormat_FileFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{0, 0}
}

type IOFileFormat_Compression int32

const (
	IOFileFormat_Auto IOFileFormat_Compression = 0
	IOFileFormat_None IOFileFormat_Compression = 1
	IOFileFormat_Gzip IOFileFormat_Compression = 2
	IOFileFormat_Bzip IOFileFormat_Compression = 3
)

var IOFileFormat_Compression_name = map[int32]string{
	0: "Auto",
	1: "None",
	2: "Gzip",
	3: "Bzip",
}
var IOFileFormat_Compression_value = map[string]int32{
	"Auto": 0,
	"None": 1,
	"Gzip": 2,
	"Bzip": 3,
}

func (x IOFileFormat_Compression) Enum() *IOFileFormat_Compression {
	p := new(IOFileFormat_Compression)
	*p = x
	return p
}
func (x IOFileFormat_Compression) String() string {
	return proto.EnumName(IOFileFormat_Compression_name, int32(x))
}
func (x *IOFileFormat_Compression) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IOFileFormat_Compression_value, data, "IOFileFormat_Compression")
	if err != nil {
		return err
	}
	*x = IOFileFormat_Compression(value)
	return nil
}
func (IOFileFormat_Compression) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{0, 1}
}

type CSVOptions_Enclose int32

const (
	CSVOptions_Never    CSVOptions_Enclose = 0
	CSVOptions_Always   CSVOptions_Enclose = 1
	CSVOptions_Optional CSVOptions_Enclose = 2
)

var CSVOptions_Enclose_name = map[int32]string{
	0: "Never",
	1: "Always",
	2: "Optional",
}
var CSVOptions_Enclose_value = map[string]int32{
	"Never":    0,
	"Always":   1,
	"Optional": 2,
}

func (x CSVOptions_Enclose) Enum() *CSVOptions_Enclose {
	p := new(CSVOptions_Enclose)
	*p = x
	return p
}
func (x CSVOptions_Enclose) String() string {
	return proto.EnumName(CSVOptions_Enclose_name, int32(x))
}
func (x *CSVOptions_Enclose) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CSVOptions_Enclose_value, data, "CSVOptions_Enclose")
	if err != nil {
		return err
	}
	*x = CSVOptions_Enclose(value)
	return nil
}
func (CSVOptions_Enclose) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{3, 0}
}

type MySQLOutfileOptions_Enclose int32

const (
	MySQLOutfileOptions_Never    MySQLOutfileOptions_Enclose = 0
	MySQLOutfileOptions_Always   MySQLOutfileOptions_Enclose = 1
	MySQLOutfileOptions_Optional MySQLOutfileOptions_Enclose = 2
)

var MySQLOutfileOptions_Enclose_name = map[int32]string{
	0: "Never",
	1: "Always",
	2: "Optional",
}
var MySQLOutfileOptions_Enclose_value = map[string]int32{
	"Never":    0,
	"Always":   1,
	"Optional": 2,
}

func (x MySQLOutfileOptions_Enclose) Enum() *MySQLOutfileOptions_Enclose {
	p := new(MySQLOutfileOptions_Enclose)
	*p = x
	return p
}
func (x MySQLOutfileOptions_Enclose) String() string {
	return proto.EnumName(MySQLOutfileOptions_Enclose_name, int32(x))
}
func (x *MySQLOutfileOptions_Enclose) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MySQLOutfileOptions_Enclose_value, data, "MySQLOutfileOptions_Enclose")
	if err != nil {
		return err
	}
	*x = MySQLOutfileOptions_Enclose(value)
	return nil
}
func (MySQLOutfileOptions_Enclose) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{5, 0}
}

type IOFileFormat struct {
	Format      IOFileFormat_FileFormat  `protobuf:"varint,1,opt,name=format,enum=znbase.roachpb.IOFileFormat_FileFormat" json:"format"`
	Csv         CSVOptions               `protobuf:"bytes,2,opt,name=csv" json:"csv"`
	MysqlOut    MySQLOutfileOptions      `protobuf:"bytes,3,opt,name=mysql_out,json=mysqlOut" json:"mysql_out"`
	PgCopy      PgCopyOptions            `protobuf:"bytes,4,opt,name=pg_copy,json=pgCopy" json:"pg_copy"`
	PgDump      PgDumpOptions            `protobuf:"bytes,6,opt,name=pg_dump,json=pgDump" json:"pg_dump"`
	Compression IOFileFormat_Compression `protobuf:"varint,5,opt,name=compression,enum=znbase.roachpb.IOFileFormat_Compression" json:"compression"`
	// If true, don't abort on failures but instead save the offending row and keep on.
	SaveRejected    bool                       `protobuf:"varint,7,opt,name=save_rejected,json=saveRejected" json:"save_rejected"`
	RejectedRows    int64                      `protobuf:"varint,8,opt,name=rejected_rows,json=rejectedRows" json:"rejected_rows"`
	RejectedAddress string                     `protobuf:"bytes,9,opt,name=rejected_address,json=rejectedAddress" json:"rejected_address"`
	MaxRejectedRows int64                      `protobuf:"varint,10,opt,name=max_rejected_rows,json=maxRejectedRows" json:"max_rejected_rows"`
	Txt             TXTOptions                 `protobuf:"bytes,11,opt,name=txt" json:"txt"`
	OnlySchema      bool                       `protobuf:"varint,12,opt,name=only_schema,json=onlySchema" json:"only_schema"`
	Kafka           KAFKAOptions               `protobuf:"bytes,13,opt,name=kafka" json:"kafka"`
	HttpHeader      string                     `protobuf:"bytes,14,opt,name=http_header,json=httpHeader" json:"http_header"`
	ConversionFunc  map[string]*ConversionFunc `protobuf:"bytes,15,rep,name=conversion_func,json=conversionFunc" json:"conversion_func,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *IOFileFormat) Reset()         { *m = IOFileFormat{} }
func (m *IOFileFormat) String() string { return proto.CompactTextString(m) }
func (*IOFileFormat) ProtoMessage()    {}
func (*IOFileFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{0}
}
func (m *IOFileFormat) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IOFileFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *IOFileFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOFileFormat.Merge(dst, src)
}
func (m *IOFileFormat) XXX_Size() int {
	return m.Size()
}
func (m *IOFileFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_IOFileFormat.DiscardUnknown(m)
}

var xxx_messageInfo_IOFileFormat proto.InternalMessageInfo

type ConversionFunc struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name"`
	Param []string `protobuf:"bytes,2,rep,name=param" json:"param,omitempty"`
}

func (m *ConversionFunc) Reset()         { *m = ConversionFunc{} }
func (m *ConversionFunc) String() string { return proto.CompactTextString(m) }
func (*ConversionFunc) ProtoMessage()    {}
func (*ConversionFunc) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{1}
}
func (m *ConversionFunc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConversionFunc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *ConversionFunc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversionFunc.Merge(dst, src)
}
func (m *ConversionFunc) XXX_Size() int {
	return m.Size()
}
func (m *ConversionFunc) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversionFunc.DiscardUnknown(m)
}

var xxx_messageInfo_ConversionFunc proto.InternalMessageInfo

// CSVOptions describe the format of csv data (delimiter, comment, etc).
type KAFKAOptions struct {
	// kafka 消费者组对应的groupID
	GroupId *string `protobuf:"bytes,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	// kafka 跳过主键冲突数据，upsert效果
	SkipPrimaryKeyConflicts bool `protobuf:"varint,2,opt,name=skip_primaryKey_conflicts,json=skipPrimaryKeyConflicts" json:"skip_primaryKey_conflicts"`
}

func (m *KAFKAOptions) Reset()         { *m = KAFKAOptions{} }
func (m *KAFKAOptions) String() string { return proto.CompactTextString(m) }
func (*KAFKAOptions) ProtoMessage()    {}
func (*KAFKAOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{2}
}
func (m *KAFKAOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KAFKAOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *KAFKAOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KAFKAOptions.Merge(dst, src)
}
func (m *KAFKAOptions) XXX_Size() int {
	return m.Size()
}
func (m *KAFKAOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_KAFKAOptions.DiscardUnknown(m)
}

var xxx_messageInfo_KAFKAOptions proto.InternalMessageInfo

// CSVOptions describe the format of csv data (delimiter, comment, etc).
type CSVOptions struct {
	// comma is an delimiter used by the CSV file; defaults to a comma.
	Comma int32 `protobuf:"varint,1,opt,name=comma" json:"comma"`
	// comment is an comment rune; zero value means comments not enabled.
	Comment int32 `protobuf:"varint,2,opt,name=comment" json:"comment"`
	// null_encoding, if not nil, is the string which identifies a NULL. Can be the empty string.
	NullEncoding *string `protobuf:"bytes,3,opt,name=null_encoding,json=nullEncoding" json:"null_encoding,omitempty"`
	// skip the first N lines of the input (e.g. to ignore column headers) when reading.
	Skip      uint32 `protobuf:"varint,4,opt,name=skip" json:"skip"`
	Null      string `protobuf:"bytes,5,opt,name=Null" json:"Null"`
	Rowma     int32  `protobuf:"varint,6,opt,name=rowma" json:"rowma"`
	HasEscape bool   `protobuf:"varint,7,opt,name=has_escape,json=hasEscape" json:"has_escape"`
	// escape is the character used to prefix the other delimiters (--fields-escaped-by)
	Escape  int32              `protobuf:"varint,8,opt,name=escape" json:"escape"`
	Enclose CSVOptions_Enclose `protobuf:"varint,9,opt,name=enclose,enum=znbase.roachpb.CSVOptions_Enclose" json:"enclose"`
	// encloser is the character used to enclose (qupte) fields (--fields-enclosed-by)
	Encloser int32  `protobuf:"varint,10,opt,name=encloser" json:"encloser"`
	Encoding string `protobuf:"bytes,11,opt,name=encoding" json:"encoding"`
}

func (m *CSVOptions) Reset()         { *m = CSVOptions{} }
func (m *CSVOptions) String() string { return proto.CompactTextString(m) }
func (*CSVOptions) ProtoMessage()    {}
func (*CSVOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{3}
}
func (m *CSVOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CSVOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *CSVOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVOptions.Merge(dst, src)
}
func (m *CSVOptions) XXX_Size() int {
	return m.Size()
}
func (m *CSVOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CSVOptions proto.InternalMessageInfo

type TXTOptions struct {
	// comma is an delimiter used by the CSV file; defaults to a comma.
	Comma int32 `protobuf:"varint,1,opt,name=comma" json:"comma"`
	// comment is an comment rune; zero value means comments not enabled.
	Comment int32 `protobuf:"varint,2,opt,name=comment" json:"comment"`
	// null_encoding, if not nil, is the string which identifies a NULL. Can be the empty string.
	NullEncoding *string `protobuf:"bytes,3,opt,name=null_encoding,json=nullEncoding" json:"null_encoding,omitempty"`
	// skip the first N lines of the input (e.g. to ignore column headers) when reading.
	Skip     uint32 `protobuf:"varint,4,opt,name=skip" json:"skip"`
	Null     string `protobuf:"bytes,5,opt,name=Null" json:"Null"`
	Encoding string `protobuf:"bytes,6,opt,name=encoding" json:"encoding"`
}

func (m *TXTOptions) Reset()         { *m = TXTOptions{} }
func (m *TXTOptions) String() string { return proto.CompactTextString(m) }
func (*TXTOptions) ProtoMessage()    {}
func (*TXTOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{4}
}
func (m *TXTOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TXTOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *TXTOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXTOptions.Merge(dst, src)
}
func (m *TXTOptions) XXX_Size() int {
	return m.Size()
}
func (m *TXTOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TXTOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TXTOptions proto.InternalMessageInfo

// MySQLOutfileOptions describe the format of mysql's outfile.
type MySQLOutfileOptions struct {
	// row_separator is the delimiter between rows (mysql's --rows-terminated-by)
	RowSeparator int32 `protobuf:"varint,1,opt,name=row_separator,json=rowSeparator" json:"row_separator"`
	// field_separator is the delimiter between fields (mysql's --fields-terminated-by)
	FieldSeparator int32 `protobuf:"varint,2,opt,name=field_separator,json=fieldSeparator" json:"field_separator"`
	// enclose is the enclosing (quoting) behavior (i.e. if specified and if optional).
	Enclose MySQLOutfileOptions_Enclose `protobuf:"varint,3,opt,name=enclose,enum=znbase.roachpb.MySQLOutfileOptions_Enclose" json:"enclose"`
	// encloser is the character used to enclose (qupte) fields (--fields-enclosed-by)
	Encloser int32 `protobuf:"varint,4,opt,name=encloser" json:"encloser"`
	// has_escape indicates that an escape character is set (mysql's default is not).
	HasEscape bool `protobuf:"varint,5,opt,name=has_escape,json=hasEscape" json:"has_escape"`
	// escape is the character used to prefix the other delimiters (--fields-escaped-by)
	Escape int32 `protobuf:"varint,6,opt,name=escape" json:"escape"`
}

func (m *MySQLOutfileOptions) Reset()         { *m = MySQLOutfileOptions{} }
func (m *MySQLOutfileOptions) String() string { return proto.CompactTextString(m) }
func (*MySQLOutfileOptions) ProtoMessage()    {}
func (*MySQLOutfileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{5}
}
func (m *MySQLOutfileOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MySQLOutfileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *MySQLOutfileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MySQLOutfileOptions.Merge(dst, src)
}
func (m *MySQLOutfileOptions) XXX_Size() int {
	return m.Size()
}
func (m *MySQLOutfileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MySQLOutfileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MySQLOutfileOptions proto.InternalMessageInfo

// PgCopyOptions describe the format of postgresql's COPY TO STDOUT.
type PgCopyOptions struct {
	// delimiter is the delimitor between columns (DELIMITER)
	Delimiter int32 `protobuf:"varint,1,opt,name=delimiter" json:"delimiter"`
	// null is the NULL value (NULL)
	Null string `protobuf:"bytes,2,opt,name=null" json:"null"`
	// maxRowSize is the maximum row size
	MaxRowSize int32 `protobuf:"varint,3,opt,name=maxRowSize" json:"maxRowSize"`
}

func (m *PgCopyOptions) Reset()         { *m = PgCopyOptions{} }
func (m *PgCopyOptions) String() string { return proto.CompactTextString(m) }
func (*PgCopyOptions) ProtoMessage()    {}
func (*PgCopyOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{6}
}
func (m *PgCopyOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PgCopyOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *PgCopyOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PgCopyOptions.Merge(dst, src)
}
func (m *PgCopyOptions) XXX_Size() int {
	return m.Size()
}
func (m *PgCopyOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PgCopyOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PgCopyOptions proto.InternalMessageInfo

// PgDumpOptions describe the format of postgresql's pg_dump.
type PgDumpOptions struct {
	// maxRowSize is the maximum row size
	MaxRowSize int32 `protobuf:"varint,1,opt,name=maxRowSize" json:"maxRowSize"`
}

func (m *PgDumpOptions) Reset()         { *m = PgDumpOptions{} }
func (m *PgDumpOptions) String() string { return proto.CompactTextString(m) }
func (*PgDumpOptions) ProtoMessage()    {}
func (*PgDumpOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_io_formats_803508a98c1eac5a, []int{7}
}
func (m *PgDumpOptions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PgDumpOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalTo(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (dst *PgDumpOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PgDumpOptions.Merge(dst, src)
}
func (m *PgDumpOptions) XXX_Size() int {
	return m.Size()
}
func (m *PgDumpOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PgDumpOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PgDumpOptions proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IOFileFormat)(nil), "znbase.roachpb.IOFileFormat")
	proto.RegisterMapType((map[string]*ConversionFunc)(nil), "znbase.roachpb.IOFileFormat.ConversionFuncEntry")
	proto.RegisterType((*ConversionFunc)(nil), "znbase.roachpb.ConversionFunc")
	proto.RegisterType((*KAFKAOptions)(nil), "znbase.roachpb.KAFKAOptions")
	proto.RegisterType((*CSVOptions)(nil), "znbase.roachpb.CSVOptions")
	proto.RegisterType((*TXTOptions)(nil), "znbase.roachpb.TXTOptions")
	proto.RegisterType((*MySQLOutfileOptions)(nil), "znbase.roachpb.MySQLOutfileOptions")
	proto.RegisterType((*PgCopyOptions)(nil), "znbase.roachpb.PgCopyOptions")
	proto.RegisterType((*PgDumpOptions)(nil), "znbase.roachpb.PgDumpOptions")
	proto.RegisterEnum("znbase.roachpb.DUMPFileFormat", DUMPFileFormat_name, DUMPFileFormat_value)
	proto.RegisterEnum("znbase.roachpb.IOFileFormat_FileFormat", IOFileFormat_FileFormat_name, IOFileFormat_FileFormat_value)
	proto.RegisterEnum("znbase.roachpb.IOFileFormat_Compression", IOFileFormat_Compression_name, IOFileFormat_Compression_value)
	proto.RegisterEnum("znbase.roachpb.CSVOptions_Enclose", CSVOptions_Enclose_name, CSVOptions_Enclose_value)
	proto.RegisterEnum("znbase.roachpb.MySQLOutfileOptions_Enclose", MySQLOutfileOptions_Enclose_name, MySQLOutfileOptions_Enclose_value)
}
func (m *IOFileFormat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IOFileFormat) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Format))
	dAtA[i] = 0x12
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Csv.Size()))
	n1, err := m.Csv.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x1a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.MysqlOut.Size()))
	n2, err := m.MysqlOut.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x22
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.PgCopy.Size()))
	n3, err := m.PgCopy.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	dAtA[i] = 0x28
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Compression))
	dAtA[i] = 0x32
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.PgDump.Size()))
	n4, err := m.PgDump.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	dAtA[i] = 0x38
	i++
	if m.SaveRejected {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x40
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.RejectedRows))
	dAtA[i] = 0x4a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.RejectedAddress)))
	i += copy(dAtA[i:], m.RejectedAddress)
	dAtA[i] = 0x50
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.MaxRejectedRows))
	dAtA[i] = 0x5a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Txt.Size()))
	n5, err := m.Txt.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	dAtA[i] = 0x60
	i++
	if m.OnlySchema {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x6a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Kafka.Size()))
	n6, err := m.Kafka.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	dAtA[i] = 0x72
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.HttpHeader)))
	i += copy(dAtA[i:], m.HttpHeader)
	if len(m.ConversionFunc) > 0 {
		keysForConversionFunc := make([]string, 0, len(m.ConversionFunc))
		for k := range m.ConversionFunc {
			keysForConversionFunc = append(keysForConversionFunc, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForConversionFunc)
		for _, k := range keysForConversionFunc {
			dAtA[i] = 0x7a
			i++
			v := m.ConversionFunc[string(k)]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovIoFormats(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovIoFormats(uint64(len(k))) + msgSize
			i = encodeVarintIoFormats(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintIoFormats(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintIoFormats(dAtA, i, uint64(v.Size()))
				n7, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n7
			}
		}
	}
	return i, nil
}

func (m *ConversionFunc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConversionFunc) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.Name)))
	i += copy(dAtA[i:], m.Name)
	if len(m.Param) > 0 {
		for _, s := range m.Param {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *KAFKAOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KAFKAOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.GroupId != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintIoFormats(dAtA, i, uint64(len(*m.GroupId)))
		i += copy(dAtA[i:], *m.GroupId)
	}
	dAtA[i] = 0x10
	i++
	if m.SkipPrimaryKeyConflicts {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	return i, nil
}

func (m *CSVOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CSVOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Comma))
	dAtA[i] = 0x10
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Comment))
	if m.NullEncoding != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintIoFormats(dAtA, i, uint64(len(*m.NullEncoding)))
		i += copy(dAtA[i:], *m.NullEncoding)
	}
	dAtA[i] = 0x20
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Skip))
	dAtA[i] = 0x2a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.Null)))
	i += copy(dAtA[i:], m.Null)
	dAtA[i] = 0x30
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Rowma))
	dAtA[i] = 0x38
	i++
	if m.HasEscape {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x40
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Escape))
	dAtA[i] = 0x48
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Enclose))
	dAtA[i] = 0x50
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Encloser))
	dAtA[i] = 0x5a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.Encoding)))
	i += copy(dAtA[i:], m.Encoding)
	return i, nil
}

func (m *TXTOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TXTOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Comma))
	dAtA[i] = 0x10
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Comment))
	if m.NullEncoding != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintIoFormats(dAtA, i, uint64(len(*m.NullEncoding)))
		i += copy(dAtA[i:], *m.NullEncoding)
	}
	dAtA[i] = 0x20
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Skip))
	dAtA[i] = 0x2a
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.Null)))
	i += copy(dAtA[i:], m.Null)
	dAtA[i] = 0x32
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.Encoding)))
	i += copy(dAtA[i:], m.Encoding)
	return i, nil
}

func (m *MySQLOutfileOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MySQLOutfileOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.RowSeparator))
	dAtA[i] = 0x10
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.FieldSeparator))
	dAtA[i] = 0x18
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Enclose))
	dAtA[i] = 0x20
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Encloser))
	dAtA[i] = 0x28
	i++
	if m.HasEscape {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x30
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Escape))
	return i, nil
}

func (m *PgCopyOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PgCopyOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.Delimiter))
	dAtA[i] = 0x12
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(len(m.Null)))
	i += copy(dAtA[i:], m.Null)
	dAtA[i] = 0x18
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.MaxRowSize))
	return i, nil
}

func (m *PgDumpOptions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PgDumpOptions) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintIoFormats(dAtA, i, uint64(m.MaxRowSize))
	return i, nil
}

func encodeVarintIoFormats(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *IOFileFormat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovIoFormats(uint64(m.Format))
	l = m.Csv.Size()
	n += 1 + l + sovIoFormats(uint64(l))
	l = m.MysqlOut.Size()
	n += 1 + l + sovIoFormats(uint64(l))
	l = m.PgCopy.Size()
	n += 1 + l + sovIoFormats(uint64(l))
	n += 1 + sovIoFormats(uint64(m.Compression))
	l = m.PgDump.Size()
	n += 1 + l + sovIoFormats(uint64(l))
	n += 2
	n += 1 + sovIoFormats(uint64(m.RejectedRows))
	l = len(m.RejectedAddress)
	n += 1 + l + sovIoFormats(uint64(l))
	n += 1 + sovIoFormats(uint64(m.MaxRejectedRows))
	l = m.Txt.Size()
	n += 1 + l + sovIoFormats(uint64(l))
	n += 2
	l = m.Kafka.Size()
	n += 1 + l + sovIoFormats(uint64(l))
	l = len(m.HttpHeader)
	n += 1 + l + sovIoFormats(uint64(l))
	if len(m.ConversionFunc) > 0 {
		for k, v := range m.ConversionFunc {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovIoFormats(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovIoFormats(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovIoFormats(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *ConversionFunc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	n += 1 + l + sovIoFormats(uint64(l))
	if len(m.Param) > 0 {
		for _, s := range m.Param {
			l = len(s)
			n += 1 + l + sovIoFormats(uint64(l))
		}
	}
	return n
}

func (m *KAFKAOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GroupId != nil {
		l = len(*m.GroupId)
		n += 1 + l + sovIoFormats(uint64(l))
	}
	n += 2
	return n
}

func (m *CSVOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovIoFormats(uint64(m.Comma))
	n += 1 + sovIoFormats(uint64(m.Comment))
	if m.NullEncoding != nil {
		l = len(*m.NullEncoding)
		n += 1 + l + sovIoFormats(uint64(l))
	}
	n += 1 + sovIoFormats(uint64(m.Skip))
	l = len(m.Null)
	n += 1 + l + sovIoFormats(uint64(l))
	n += 1 + sovIoFormats(uint64(m.Rowma))
	n += 2
	n += 1 + sovIoFormats(uint64(m.Escape))
	n += 1 + sovIoFormats(uint64(m.Enclose))
	n += 1 + sovIoFormats(uint64(m.Encloser))
	l = len(m.Encoding)
	n += 1 + l + sovIoFormats(uint64(l))
	return n
}

func (m *TXTOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovIoFormats(uint64(m.Comma))
	n += 1 + sovIoFormats(uint64(m.Comment))
	if m.NullEncoding != nil {
		l = len(*m.NullEncoding)
		n += 1 + l + sovIoFormats(uint64(l))
	}
	n += 1 + sovIoFormats(uint64(m.Skip))
	l = len(m.Null)
	n += 1 + l + sovIoFormats(uint64(l))
	l = len(m.Encoding)
	n += 1 + l + sovIoFormats(uint64(l))
	return n
}

func (m *MySQLOutfileOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovIoFormats(uint64(m.RowSeparator))
	n += 1 + sovIoFormats(uint64(m.FieldSeparator))
	n += 1 + sovIoFormats(uint64(m.Enclose))
	n += 1 + sovIoFormats(uint64(m.Encloser))
	n += 2
	n += 1 + sovIoFormats(uint64(m.Escape))
	return n
}

func (m *PgCopyOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovIoFormats(uint64(m.Delimiter))
	l = len(m.Null)
	n += 1 + l + sovIoFormats(uint64(l))
	n += 1 + sovIoFormats(uint64(m.MaxRowSize))
	return n
}

func (m *PgDumpOptions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovIoFormats(uint64(m.MaxRowSize))
	return n
}

func sovIoFormats(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozIoFormats(x uint64) (n int) {
	return sovIoFormats(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IOFileFormat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IOFileFormat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IOFileFormat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Format", wireType)
			}
			m.Format = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Format |= (IOFileFormat_FileFormat(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Csv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Csv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MysqlOut", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MysqlOut.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgCopy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PgCopy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Compression", wireType)
			}
			m.Compression = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Compression |= (IOFileFormat_Compression(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PgDump", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PgDump.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SaveRejected", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SaveRejected = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedRows", wireType)
			}
			m.RejectedRows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RejectedRows |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RejectedAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RejectedAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRejectedRows", wireType)
			}
			m.MaxRejectedRows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRejectedRows |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Txt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnlySchema", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OnlySchema = bool(v != 0)
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kafka", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Kafka.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpHeader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HttpHeader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConversionFunc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConversionFunc == nil {
				m.ConversionFunc = make(map[string]*ConversionFunc)
			}
			var mapkey string
			var mapvalue *ConversionFunc
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowIoFormats
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowIoFormats
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthIoFormats
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowIoFormats
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthIoFormats
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthIoFormats
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &ConversionFunc{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipIoFormats(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthIoFormats
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ConversionFunc[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConversionFunc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConversionFunc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConversionFunc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Param", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Param = append(m.Param, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KAFKAOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KAFKAOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KAFKAOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.GroupId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipPrimaryKeyConflicts", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SkipPrimaryKeyConflicts = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CSVOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CSVOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CSVOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comma", wireType)
			}
			m.Comma = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Comma |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
			}
			m.Comment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Comment |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NullEncoding", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.NullEncoding = &s
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skip", wireType)
			}
			m.Skip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Skip |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Null", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Null = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rowma", wireType)
			}
			m.Rowma = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rowma |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasEscape", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasEscape = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Escape", wireType)
			}
			m.Escape = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Escape |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enclose", wireType)
			}
			m.Enclose = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Enclose |= (CSVOptions_Enclose(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encloser", wireType)
			}
			m.Encloser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Encloser |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Encoding = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TXTOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TXTOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TXTOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comma", wireType)
			}
			m.Comma = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Comma |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
			}
			m.Comment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Comment |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NullEncoding", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.NullEncoding = &s
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skip", wireType)
			}
			m.Skip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Skip |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Null", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Null = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Encoding = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MySQLOutfileOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MySQLOutfileOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MySQLOutfileOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowSeparator", wireType)
			}
			m.RowSeparator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowSeparator |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldSeparator", wireType)
			}
			m.FieldSeparator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FieldSeparator |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enclose", wireType)
			}
			m.Enclose = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Enclose |= (MySQLOutfileOptions_Enclose(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encloser", wireType)
			}
			m.Encloser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Encloser |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasEscape", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasEscape = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Escape", wireType)
			}
			m.Escape = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Escape |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PgCopyOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PgCopyOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PgCopyOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delimiter", wireType)
			}
			m.Delimiter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Delimiter |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Null", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIoFormats
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Null = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRowSize", wireType)
			}
			m.MaxRowSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRowSize |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PgDumpOptions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PgDumpOptions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PgDumpOptions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRowSize", wireType)
			}
			m.MaxRowSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRowSize |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIoFormats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthIoFormats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIoFormats(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIoFormats
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIoFormats
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthIoFormats
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowIoFormats
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipIoFormats(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthIoFormats = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIoFormats   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("roachpb/io-formats.proto", fileDescriptor_io_formats_803508a98c1eac5a)
}

var fileDescriptor_io_formats_803508a98c1eac5a = []byte{
	// 1134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x8f, 0xda, 0x46,
	0x18, 0xc6, 0x98, 0x2f, 0xbf, 0xb0, 0xac, 0x3b, 0x89, 0x54, 0x67, 0x95, 0x52, 0xe4, 0xb4, 0x2a,
	0x69, 0x15, 0x36, 0x42, 0x5d, 0x29, 0xaa, 0x7a, 0x08, 0xb0, 0x6c, 0x13, 0x6d, 0xf6, 0xa3, 0x40,
	0xa2, 0x34, 0x17, 0x6b, 0x62, 0x06, 0x70, 0xb1, 0x3d, 0xae, 0x3f, 0x96, 0x65, 0x2f, 0xbd, 0xf7,
	0xd4, 0x5f, 0xd4, 0xf3, 0xf6, 0x96, 0xde, 0x72, 0xaa, 0xda, 0xdd, 0x3f, 0x52, 0xcd, 0xd8, 0x06,
	0x9b, 0x25, 0x4d, 0x7a, 0xeb, 0x6d, 0x78, 0xde, 0xe7, 0x7d, 0x66, 0xde, 0x4f, 0x03, 0x8a, 0x4b,
	0xb1, 0x3e, 0x75, 0x5e, 0xef, 0x1a, 0xf4, 0xc1, 0x98, 0xba, 0x16, 0xf6, 0xbd, 0xa6, 0xe3, 0x52,
	0x9f, 0xa2, 0xea, 0x85, 0xfd, 0x1a, 0x7b, 0xa4, 0x19, 0x11, 0x76, 0x6e, 0x4f, 0xe8, 0x84, 0x72,
	0xd3, 0x2e, 0x3b, 0x85, 0x2c, 0xf5, 0x17, 0x09, 0x2a, 0x4f, 0x4f, 0x0e, 0x0c, 0x93, 0x1c, 0x70,
	0x6f, 0xd4, 0x83, 0x42, 0xa8, 0xa3, 0x08, 0x75, 0xa1, 0x51, 0x6d, 0x7d, 0xd1, 0x4c, 0xeb, 0x34,
	0x93, 0xec, 0xe6, 0xea, 0xd8, 0xc9, 0x5d, 0xfe, 0xf9, 0x69, 0xa6, 0x1f, 0x39, 0xa3, 0x16, 0x88,
	0xba, 0x77, 0xa6, 0x64, 0xeb, 0x42, 0xa3, 0xdc, 0xda, 0x59, 0xd7, 0xe8, 0x0e, 0x5e, 0x9c, 0x38,
	0xbe, 0x41, 0x6d, 0x2f, 0x72, 0x63, 0x64, 0x74, 0x00, 0x92, 0xb5, 0xf0, 0x7e, 0x32, 0x35, 0x1a,
	0xf8, 0x8a, 0xc8, 0x3d, 0xef, 0xad, 0x7b, 0x1e, 0x2d, 0x06, 0xdf, 0x3f, 0x3b, 0x09, 0xfc, 0xb1,
	0x61, 0x92, 0xb4, 0x44, 0x89, 0xfb, 0x9e, 0x04, 0x3e, 0xfa, 0x16, 0x8a, 0xce, 0x44, 0xd3, 0xa9,
	0xb3, 0x50, 0x72, 0x5c, 0xe5, 0x93, 0x75, 0x95, 0xd3, 0x49, 0x97, 0x3a, 0x8b, 0xb4, 0x7f, 0xc1,
	0xe1, 0x20, 0x3a, 0x85, 0xb2, 0x4e, 0x2d, 0xc7, 0x25, 0x9e, 0x67, 0x50, 0x5b, 0xc9, 0xf3, 0x2c,
	0x34, 0xfe, 0x35, 0x0b, 0xdd, 0x15, 0x3f, 0x12, 0x4b, 0x4a, 0x44, 0xef, 0x19, 0x05, 0x96, 0xa3,
	0x14, 0xde, 0xf5, 0x9e, 0xfd, 0xc0, 0x72, 0x6e, 0xbc, 0x87, 0x81, 0xe8, 0x3e, 0x6c, 0x79, 0xf8,
	0x8c, 0x68, 0x2e, 0xf9, 0x91, 0xe8, 0x3e, 0x19, 0x29, 0xc5, 0xba, 0xd0, 0x28, 0x45, 0xa4, 0x0a,
	0x33, 0xf5, 0x23, 0x0b, 0xa3, 0xc6, 0x2c, 0xcd, 0xa5, 0x73, 0x4f, 0x29, 0xd5, 0x85, 0x86, 0x18,
	0x53, 0x63, 0x53, 0x9f, 0xce, 0x3d, 0xb4, 0x0b, 0xf2, 0x92, 0x8a, 0x47, 0x23, 0xf6, 0x54, 0x45,
	0xaa, 0x0b, 0x0d, 0x29, 0x62, 0x6f, 0xc7, 0xd6, 0x76, 0x68, 0x44, 0x0f, 0xe1, 0x23, 0x0b, 0x9f,
	0x6b, 0x69, 0x7d, 0x48, 0xe8, 0x6f, 0x5b, 0xf8, 0xbc, 0x9f, 0xbc, 0xa2, 0x05, 0xa2, 0x7f, 0xee,
	0x2b, 0xe5, 0xcd, 0x2d, 0x30, 0x7c, 0x39, 0x5c, 0x6b, 0x01, 0xff, 0xdc, 0x47, 0x9f, 0x43, 0x99,
	0xda, 0xe6, 0x42, 0xf3, 0xf4, 0x29, 0xb1, 0xb0, 0x52, 0x49, 0x84, 0x0a, 0xcc, 0x30, 0xe0, 0x38,
	0x7a, 0x04, 0xf9, 0x19, 0x1e, 0xcf, 0xb0, 0xb2, 0xc5, 0xc5, 0xef, 0xae, 0x8b, 0x1f, 0xb6, 0x0f,
	0x0e, 0xdb, 0x69, 0xf9, 0xd0, 0x81, 0x5d, 0x30, 0xf5, 0x7d, 0x47, 0x9b, 0x12, 0x3c, 0x22, 0xae,
	0x52, 0x4d, 0x84, 0x0c, 0xcc, 0xf0, 0x84, 0xe3, 0xe8, 0x07, 0xd8, 0xd6, 0xa9, 0x7d, 0x46, 0x5c,
	0x56, 0x40, 0x6d, 0x1c, 0xd8, 0xba, 0xb2, 0x5d, 0x17, 0x1b, 0xe5, 0xd6, 0xc3, 0xf7, 0x34, 0x42,
	0xec, 0x73, 0x10, 0xd8, 0x7a, 0xcf, 0xf6, 0xdd, 0x45, 0xbf, 0xaa, 0xa7, 0xc0, 0x1d, 0x0c, 0xb7,
	0x36, 0xd0, 0x90, 0x0c, 0xe2, 0x8c, 0x2c, 0xf8, 0xd0, 0x49, 0x7d, 0x76, 0x44, 0x5f, 0x43, 0xfe,
	0x0c, 0x9b, 0x01, 0x89, 0x86, 0xa8, 0x76, 0x63, 0x88, 0x52, 0x2a, 0xfd, 0x90, 0xfc, 0x4d, 0xf6,
	0x91, 0xa0, 0xfe, 0x0c, 0x90, 0x98, 0xe8, 0x32, 0x14, 0x9f, 0xdb, 0x33, 0x9b, 0xce, 0x6d, 0x39,
	0x83, 0x8a, 0x20, 0x76, 0x07, 0x2f, 0x64, 0x01, 0xc9, 0x50, 0x39, 0x8a, 0x06, 0x86, 0xcd, 0x92,
	0x9c, 0x45, 0x5b, 0x20, 0x71, 0x84, 0x35, 0xaa, 0x2c, 0x22, 0x80, 0x42, 0x38, 0x26, 0x72, 0x2e,
	0x3c, 0xb3, 0x6e, 0x94, 0xf3, 0x4c, 0x61, 0xf8, 0x72, 0x28, 0x17, 0x50, 0x15, 0xe0, 0xd5, 0x71,
	0x07, 0x7b, 0x64, 0xff, 0xf9, 0xd1, 0xa9, 0x5c, 0x44, 0x12, 0xe4, 0x0f, 0x59, 0x8e, 0xe5, 0x92,
	0xba, 0x07, 0xe5, 0xc4, 0x4c, 0xa0, 0x12, 0xe4, 0xda, 0x81, 0x4f, 0xe5, 0x0c, 0x3b, 0x1d, 0x53,
	0x9b, 0xc8, 0x02, 0x3b, 0x7d, 0x77, 0x61, 0x38, 0x72, 0x96, 0x9d, 0x3a, 0xec, 0x24, 0xaa, 0x8f,
	0xa1, 0x9a, 0x0e, 0x0a, 0x29, 0x90, 0xb3, 0xb1, 0x45, 0xc2, 0xb4, 0x44, 0x75, 0xe2, 0x08, 0xba,
	0x0d, 0x79, 0x07, 0xbb, 0xd8, 0x52, 0xb2, 0x75, 0xb1, 0x21, 0xf5, 0xc3, 0x1f, 0xea, 0x0c, 0x2a,
	0xc9, 0xda, 0xa3, 0x3b, 0x50, 0x9a, 0xb8, 0x34, 0x70, 0x34, 0x63, 0x14, 0xa5, 0xb6, 0xc8, 0x7f,
	0x3f, 0x1d, 0xa1, 0xc7, 0x70, 0xc7, 0x9b, 0x19, 0x8e, 0xe6, 0xb8, 0x86, 0x85, 0xdd, 0xc5, 0x21,
	0x59, 0x68, 0x3a, 0xb5, 0xc7, 0xa6, 0xa1, 0xfb, 0x1e, 0x4f, 0x79, 0xdc, 0x78, 0x1f, 0x33, 0xda,
	0xe9, 0x92, 0xd5, 0x8d, 0x49, 0xea, 0x6f, 0x22, 0xc0, 0x6a, 0x93, 0xa1, 0x1d, 0xc8, 0xeb, 0xd4,
	0xb2, 0x30, 0xbf, 0x28, 0x1f, 0xb7, 0x1d, 0x87, 0x50, 0x0d, 0x8a, 0xec, 0x40, 0x6c, 0x9f, 0x4b,
	0xc7, 0xd6, 0x18, 0x64, 0x93, 0x6b, 0x07, 0xa6, 0xa9, 0x11, 0x5b, 0xa7, 0x23, 0xc3, 0x9e, 0xf0,
	0xf5, 0x17, 0x06, 0x2c, 0xf4, 0x2b, 0xcc, 0xd4, 0x8b, 0x2c, 0x2c, 0x25, 0xec, 0x41, 0x7c, 0xb5,
	0x6d, 0xc5, 0x29, 0x61, 0x08, 0xb3, 0x1c, 0x07, 0xa6, 0xc9, 0x57, 0xd6, 0x32, 0x59, 0x0c, 0x61,
	0x4f, 0x73, 0xe9, 0xdc, 0xc2, 0x7c, 0xff, 0x2c, 0x9f, 0xc6, 0x21, 0x74, 0x0f, 0x60, 0x8a, 0x3d,
	0x8d, 0x78, 0x3a, 0x76, 0x48, 0x6a, 0xb9, 0x48, 0x53, 0xec, 0xf5, 0x38, 0x8c, 0xee, 0x42, 0x21,
	0x22, 0x94, 0x12, 0x0a, 0x11, 0x86, 0x3a, 0x50, 0x24, 0xb6, 0x6e, 0x52, 0x8f, 0xf0, 0x1d, 0x52,
	0x6d, 0xa9, 0xef, 0x5e, 0xf8, 0xcd, 0x5e, 0xc8, 0x8c, 0x33, 0x10, 0x39, 0xa2, 0x3a, 0x94, 0xa2,
	0xa3, 0xcb, 0xd7, 0x4a, 0x7c, 0xc7, 0x12, 0x8d, 0x18, 0x61, 0x7a, 0xca, 0x89, 0x10, 0x97, 0xa8,
	0xda, 0x84, 0x62, 0xa4, 0xce, 0x9a, 0xf1, 0x98, 0x9c, 0x11, 0x57, 0xce, 0xb0, 0xe6, 0x6d, 0x9b,
	0x73, 0xbc, 0xf0, 0x64, 0x01, 0x55, 0xa0, 0x14, 0xbe, 0x03, 0x9b, 0x72, 0x56, 0xfd, 0x5d, 0x00,
	0x58, 0xed, 0xa1, 0xff, 0x73, 0x01, 0x93, 0xb1, 0x17, 0x36, 0xc6, 0xfe, 0x47, 0x16, 0x6e, 0x6d,
	0xf8, 0x38, 0xf2, 0x6f, 0x02, 0x9d, 0x6b, 0x1e, 0x61, 0x03, 0xe2, 0x53, 0x37, 0x15, 0x5c, 0xc5,
	0xa5, 0xf3, 0x41, 0x6c, 0x41, 0x0f, 0x60, 0x7b, 0x6c, 0x10, 0x73, 0x94, 0x20, 0x27, 0x63, 0xad,
	0x72, 0xe3, 0x8a, 0x7e, 0xb8, 0xaa, 0xba, 0xc8, 0xab, 0xfe, 0xd5, 0x07, 0x7c, 0xac, 0x3f, 0xa4,
	0xfc, 0xb9, 0x8d, 0xe5, 0x4f, 0xf7, 0x69, 0xfe, 0x7d, 0x7d, 0x5a, 0xb8, 0xd9, 0xa7, 0xff, 0xb9,
	0x3f, 0x3c, 0xd8, 0x4a, 0xfd, 0x53, 0x40, 0x2a, 0x48, 0x23, 0x62, 0x1a, 0x96, 0xe1, 0x93, 0x74,
	0x22, 0x57, 0x30, 0x5f, 0x59, 0xac, 0x88, 0xd9, 0xd4, 0xca, 0x62, 0x45, 0xfc, 0x0c, 0x80, 0x7d,
	0x23, 0xe9, 0x7c, 0x60, 0x5c, 0x84, 0x39, 0x8b, 0xdd, 0x13, 0xb8, 0xba, 0xc7, 0x2e, 0x4d, 0xfc,
	0x1d, 0x58, 0x73, 0x13, 0x36, 0xbb, 0x7d, 0xb9, 0x07, 0x55, 0xb6, 0x87, 0x13, 0x7b, 0x5f, 0x82,
	0xfc, 0xb0, 0xdd, 0x79, 0xd6, 0x93, 0x33, 0x2c, 0xac, 0xfd, 0xf6, 0xb0, 0xdd, 0x69, 0x0f, 0x7a,
	0xb2, 0xc0, 0x02, 0x1e, 0x74, 0x9f, 0xf4, 0x8e, 0xda, 0x72, 0xb6, 0x73, 0xff, 0xf2, 0xef, 0x5a,
	0xe6, 0xf2, 0xaa, 0x26, 0xbc, 0xb9, 0xaa, 0x09, 0x6f, 0xaf, 0x6a, 0xc2, 0x5f, 0x57, 0x35, 0xe1,
	0xd7, 0xeb, 0x5a, 0xe6, 0xcd, 0x75, 0x2d, 0xf3, 0xf6, 0xba, 0x96, 0x79, 0x55, 0x8c, 0xaa, 0xf9,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xd3, 0xb4, 0x57, 0x6b, 0x0a, 0x00, 0x00,
}
